import type { DashboardData } from "@/lib/sales-dashboard/types";

/** Sample snapshot from the original HTML dashboard — used until Graph is configured. */
export function getDemoDashboard(): DashboardData {
  return {
    active: 373,
    premium: 83854,
    pending: 46,
    issues: 59,
    sales: {
      labels: ["דצ 2025", "ינו 2026", "פבר 2026", "מרץ 2026"],
      counts: [3, 110, 90, 70],
      sums: [413, 26000, 21000, 16000],
    },
    appointments: {
      labels: ["דצ 2025", "ינו 2026", "פבר 2026", "מרץ 2026"],
      counts: [0, 31, 30, 26],
      sums: [0, 8140, 6852, 5449],
    },
    currentMonth: {
      label: "מרץ 2026",
      totalCount: 70,
      totalSum: 16000,
      activeCount: 56,
      activeSum: 13200,
    },
    agents: [
      { name: "ניב קובי", count: 44, sum: 10046 },
      { name: "שמש", count: 39, sum: 10115 },
      { name: "אסף בר און", count: 43, sum: 8279 },
      { name: "סימונה", count: 34, sum: 7882 },
      { name: "בן ביטון", count: 26, sum: 6616 },
      { name: "ניב - שמש", count: 23, sum: 6478 },
      { name: "חן בר און", count: 25, sum: 4255 },
      { name: "אוריאל כהן", count: 24, sum: 4241 },
    ],
    monthAgents: [
      { name: "שמש", count: 18, sum: 4200 },
      { name: "ניב קובי", count: 16, sum: 3800 },
      { name: "סימונה", count: 12, sum: 2650 },
      { name: "אסף בר און", count: 11, sum: 2400 },
      { name: "אוריאל כהן", count: 8, sum: 1450 },
      { name: "בן ביטון", count: 7, sum: 1100 },
      { name: "חן בר און", count: 5, sum: 250 },
      { name: "ניב - שמש", count: 4, sum: 150 },
    ],
    companies: [
      { name: "מגדל", count: 140 },
      { name: "הראל", count: 136 },
      { name: "הפניקס", count: 119 },
      { name: "כלל", count: 77 },
      { name: "איילון", count: 22 },
      { name: "מנורה", count: 16 },
      { name: "הכשרה", count: 12 },
    ],
    sources: [
      { name: "לקוחות ליבה", count: 119 },
      { name: "שיחות נכנסות", count: 109 },
      { name: "רועי אזולאי", count: 84 },
      { name: "קפמיין אישי", count: 50 },
      { name: "לידים קרים", count: 27 },
      { name: "קמפיין שמש", count: 17 },
      { name: "אורשן משכנתאות", count: 11 },
    ],
    pendingRows: [
      {
        name: "חיים פאטיטיף",
        agent: "אוריאל כהן",
        product: "אכ\"ע",
        premium: 1450,
        date: "2026-03-12",
      },
      {
        name: "תקווה פרץ",
        agent: "רועי ברודוגו",
        product: "משכנתא",
        premium: 1348,
        date: "2026-03-04",
      },
      {
        name: "מוחמד אבו ראס",
        agent: "ניב קובי",
        product: "תאונות",
        premium: 606,
        date: "2026-03-17",
      },
      {
        name: "ריבה טיטשוולי",
        agent: "ניב קובי",
        product: "משכנתא",
        premium: 580,
        date: "2026-02-17",
      },
      {
        name: "חיכמת עבאס",
        agent: "אוריאל כהן",
        product: "משכנתא",
        premium: 500,
        date: "2026-03-25",
      },
      {
        name: "סימה אהרוני",
        agent: "אוריאל כהן",
        product: "בריאות",
        premium: 500,
        date: "2026-03-29",
      },
      {
        name: "אפרת ג'ובני",
        agent: "שמש",
        product: "בריאות",
        premium: 399,
        date: "2026-03-10",
      },
      {
        name: "סיגלית אלון",
        agent: "שמש",
        product: "בריאות",
        premium: 314,
        date: "2026-03-25",
      },
    ],
    activePolicies: [
      {
        key: "demo|בריאות|ניב קובי|2026-03-01",
        client: "ישראל ישראלי",
        product: "בריאות + מחלות קשות",
        company: "מגדל",
        premium: 1850,
        agent: "ניב קובי",
      },
    ],
    marketing: {
      activeCount: 373,
      activePremium: 83854,
      pendingCount: 46,
      pendingPremium: 12480,
      cancelledCount: 59,
      cancelledPremium: 9800,
      sources: [
        {
          name: "התפתחות הילד",
          activeCount: 84,
          activePremium: 22140,
          pendingCount: 9,
          pendingPremium: 2400,
          agents: [
            { name: "ניב קובי", count: 22, sum: 6100 },
            { name: "שמש", count: 18, sum: 5400 },
            { name: "סימונה", count: 16, sum: 4200 },
            { name: "אסף בר און", count: 14, sum: 3800 },
            { name: "חן בר און", count: 14, sum: 2640 },
          ],
          months: [
            { name: "01/2026", count: 18, sum: 4800 },
            { name: "02/2026", count: 28, sum: 7400 },
            { name: "03/2026", count: 38, sum: 9940 },
          ],
          products: [
            { name: "בריאות", count: 40, sum: 11200 },
            { name: "משכנתא", count: 24, sum: 6800 },
            { name: "תאונות", count: 20, sum: 4140 },
          ],
          companies: [
            { name: "מגדל", count: 32, sum: 8600 },
            { name: "הראל", count: 28, sum: 7400 },
            { name: "הפניקס", count: 24, sum: 6140 },
          ],
        },
        {
          name: "לקוחות ליבה",
          activeCount: 119,
          activePremium: 24800,
          pendingCount: 12,
          pendingPremium: 3100,
          agents: [
            { name: "שמש", count: 30, sum: 7200 },
            { name: "ניב קובי", count: 28, sum: 6800 },
            { name: "אסף בר און", count: 24, sum: 5400 },
            { name: "סימונה", count: 20, sum: 3200 },
            { name: "אוריאל כהן", count: 17, sum: 2200 },
          ],
          months: [
            { name: "01/2026", count: 40, sum: 8200 },
            { name: "02/2026", count: 39, sum: 8100 },
            { name: "03/2026", count: 40, sum: 8500 },
          ],
          products: [
            { name: "בריאות", count: 50, sum: 11000 },
            { name: "משכנתא", count: 40, sum: 8800 },
            { name: "אכ\"ע", count: 29, sum: 5000 },
          ],
          companies: [
            { name: "הראל", count: 44, sum: 9200 },
            { name: "מגדל", count: 40, sum: 8600 },
            { name: "כלל", count: 35, sum: 7000 },
          ],
        },
        {
          name: "שיחות נכנסות",
          activeCount: 109,
          activePremium: 19600,
          pendingCount: 11,
          pendingPremium: 2800,
          agents: [
            { name: "ניב קובי", count: 24, sum: 5100 },
            { name: "בן ביטון", count: 22, sum: 4600 },
            { name: "אוריאל כהן", count: 21, sum: 3900 },
            { name: "סימונה", count: 22, sum: 3200 },
            { name: "חן בר און", count: 20, sum: 2800 },
          ],
          months: [
            { name: "01/2026", count: 30, sum: 5400 },
            { name: "02/2026", count: 38, sum: 6800 },
            { name: "03/2026", count: 41, sum: 7400 },
          ],
          products: [
            { name: "משכנתא", count: 48, sum: 9200 },
            { name: "בריאות", count: 36, sum: 6400 },
            { name: "תאונות", count: 25, sum: 4000 },
          ],
          companies: [
            { name: "מגדל", count: 40, sum: 7400 },
            { name: "הפניקס", count: 38, sum: 6800 },
            { name: "הראל", count: 31, sum: 5400 },
          ],
        },
        {
          name: "קמפיין שמש",
          activeCount: 17,
          activePremium: 4100,
          pendingCount: 4,
          pendingPremium: 980,
          agents: [{ name: "שמש", count: 17, sum: 4100 }],
          months: [
            { name: "02/2026", count: 7, sum: 1600 },
            { name: "03/2026", count: 10, sum: 2500 },
          ],
          products: [{ name: "בריאות", count: 17, sum: 4100 }],
          companies: [{ name: "מגדל", count: 17, sum: 4100 }],
        },
        {
          name: "לידים קרים",
          activeCount: 27,
          activePremium: 6840,
          pendingCount: 6,
          pendingPremium: 1800,
          agents: [
            { name: "אסף בר און", count: 15, sum: 3800 },
            { name: "ניב - שמש", count: 12, sum: 3040 },
          ],
          months: [
            { name: "01/2026", count: 9, sum: 2200 },
            { name: "02/2026", count: 10, sum: 2400 },
            { name: "03/2026", count: 8, sum: 2240 },
          ],
          products: [
            { name: "תאונות", count: 15, sum: 3600 },
            { name: "בריאות", count: 12, sum: 3240 },
          ],
          companies: [
            { name: "כלל", count: 14, sum: 3600 },
            { name: "איילון", count: 13, sum: 3240 },
          ],
        },
        {
          name: "קפמיין אישי",
          activeCount: 17,
          activePremium: 6374,
          pendingCount: 4,
          pendingPremium: 1400,
          agents: [
            { name: "ניב - שמש", count: 10, sum: 3600 },
            { name: "חן בר און", count: 7, sum: 2774 },
          ],
          months: [
            { name: "02/2026", count: 8, sum: 3000 },
            { name: "03/2026", count: 9, sum: 3374 },
          ],
          products: [{ name: "בריאות", count: 17, sum: 6374 }],
          companies: [{ name: "הפניקס", count: 17, sum: 6374 }],
        },
      ],
      sourceCatalog: [
        "התפתחות הילד",
        "לקוחות ליבה",
        "שיחות נכנסות",
        "קפמיין אישי",
        "קמפיין שמש",
      ],
      sellerCatalog: [
        "אוריאל כהן",
        "אסף בר און",
        "בן ביטון",
        "חן בר און",
        "ניב - שמש",
        "ניב קובי",
        "סימונה",
        "שמש",
      ],
      excelHeaders: [
        "סטאטוס פוליסה",
        "פרמיה",
        "סוג תהליך",
        "תאריך העברה ליצרן",
        "תאריך תחילת ביטוח",
        "שם לקוח",
        "משווק",
        "סוג המוצר",
        "חברת הביטוח",
        "מקור הפנייה",
      ],
      productions: [
        {
          key: "demo|ילד|ניב|2026-03-01",
          source: "התפתחות הילד",
          client: "משפחת כהן",
          agent: "ניב קובי",
          product: "בריאות",
          company: "מגדל",
          premium: 1850,
          status: "active",
          statusRaw: "פעילה",
          process: "מכירה",
          startDate: "2026-04-01",
          transferDate: "2026-03-04",
          fields: {
            "סטאטוס פוליסה": "פעילה",
            פרמיה: "1850",
            "סוג תהליך": "מכירה",
            "תאריך העברה ליצרן": "2026-03-04",
            "שם לקוח": "משפחת כהן",
            משווק: "ניב קובי",
            "סוג המוצר": "בריאות",
            "חברת הביטוח": "מגדל",
            "מקור הפנייה": "התפתחות הילד",
          },
        },
        {
          key: "demo|ילד|שמש|2026-03-08",
          source: "התפתחות הילד",
          client: "משפחת לוי",
          agent: "שמש",
          product: "בריאות",
          company: "הראל",
          premium: 1420,
          status: "active",
          statusRaw: "פעילה",
          process: "מכירה",
          startDate: "2026-04-01",
          transferDate: "2026-03-08",
          fields: {
            "סטאטוס פוליסה": "פעילה",
            פרמיה: "1420",
            "סוג תהליך": "מכירה",
            "תאריך העברה ליצרן": "2026-03-08",
            "שם לקוח": "משפחת לוי",
            משווק: "שמש",
            "סוג המוצר": "בריאות",
            "חברת הביטוח": "הראל",
            "מקור הפנייה": "התפתחות הילד",
          },
        },
        {
          key: "demo|ילד|סימונה|2026-03-12",
          source: "התפתחות הילד",
          client: "משפחת אברהם",
          agent: "סימונה",
          product: "משכנתא",
          company: "הפניקס",
          premium: 980,
          status: "pending",
          statusRaw: "ממתינה למינוי",
          process: "מינוי",
          startDate: "2026-04-01",
          transferDate: "2026-03-12",
          fields: {
            "סטאטוס פוליסה": "ממתינה למינוי",
            פרמיה: "980",
            "סוג תהליך": "מינוי",
            "תאריך העברה ליצרן": "2026-03-12",
            "שם לקוח": "משפחת אברהם",
            משווק: "סימונה",
            "סוג המוצר": "משכנתא",
            "חברת הביטוח": "הפניקס",
            "מקור הפנייה": "התפתחות הילד",
          },
        },
        {
          key: "demo|אישי|חן|2026-03-02",
          source: "קפמיין אישי",
          client: "דנה מזרחי",
          agent: "חן בר און",
          product: "בריאות",
          company: "הפניקס",
          premium: 2100,
          status: "active",
          statusRaw: "פעילה",
          process: "מכירה",
          startDate: "2026-04-01",
          transferDate: "2026-03-02",
          fields: {
            "סטאטוס פוליסה": "פעילה",
            פרמיה: "2100",
            "סוג תהליך": "מכירה",
            "תאריך העברה ליצרן": "2026-03-02",
            "שם לקוח": "דנה מזרחי",
            משווק: "חן בר און",
            "סוג המוצר": "בריאות",
            "חברת הביטוח": "הפניקס",
            "מקור הפנייה": "קפמיין אישי",
          },
        },
        {
          key: "demo|שמש|שמש|2026-02-20",
          source: "קמפיין שמש",
          client: "יוסי דהן",
          agent: "שמש",
          product: "בריאות",
          company: "מגדל",
          premium: 1600,
          status: "active",
          statusRaw: "פעילה",
          process: "מכירה",
          startDate: "2026-03-01",
          transferDate: "2026-02-20",
          fields: {
            "סטאטוס פוליסה": "פעילה",
            פרמיה: "1600",
            "סוג תהליך": "מכירה",
            "תאריך העברה ליצרן": "2026-02-20",
            "שם לקוח": "יוסי דהן",
            משווק: "שמש",
            "סוג המוצר": "בריאות",
            "חברת הביטוח": "מגדל",
            "מקור הפנייה": "קמפיין שמש",
          },
        },
      ],
      agents: [
        { name: "ניב קובי", count: 44, sum: 10046 },
        { name: "שמש", count: 39, sum: 10115 },
        { name: "אסף בר און", count: 43, sum: 8279 },
        { name: "סימונה", count: 34, sum: 7882 },
        { name: "בן ביטון", count: 26, sum: 6616 },
        { name: "ניב - שמש", count: 23, sum: 6478 },
        { name: "חן בר און", count: 25, sum: 4255 },
        { name: "אוריאל כהן", count: 24, sum: 4241 },
      ],
      months: [
        { name: "12/2025", count: 3, sum: 413 },
        { name: "01/2026", count: 110, sum: 26000 },
        { name: "02/2026", count: 90, sum: 21000 },
        { name: "03/2026", count: 70, sum: 16000 },
      ],
      products: [
        { name: "בריאות", count: 160, sum: 36000 },
        { name: "משכנתא", count: 112, sum: 24800 },
        { name: "תאונות", count: 60, sum: 14000 },
        { name: "אכ\"ע", count: 41, sum: 9054 },
      ],
      companies: [
        { name: "מגדל", count: 140, sum: 31000 },
        { name: "הראל", count: 136, sum: 24800 },
        { name: "הפניקס", count: 119, sum: 18000 },
        { name: "כלל", count: 77, sum: 10054 },
      ],
    },
    fileName: null,
    syncedAt: new Date().toISOString(),
    source: "demo",
  };
}
