import type { DashboardData } from "@/lib/sales-dashboard/types";

/** Sample snapshot from the original HTML dashboard — used until Graph is configured. */
export function getDemoDashboard(): DashboardData {
  return {
    active: 373,
    premium: 83854,
    pending: 46,
    issues: 59,
    sales: {
      labels: ["דצ 2025", "ינו 2026", "פבר 2026", "מרץ 2026"],
      counts: [3, 110, 90, 70],
      sums: [413, 26000, 21000, 16000],
    },
    appointments: {
      labels: ["דצ 2025", "ינו 2026", "פבר 2026", "מרץ 2026"],
      counts: [0, 31, 30, 26],
      sums: [0, 8140, 6852, 5449],
    },
    currentMonth: {
      label: "מרץ 2026",
      totalCount: 70,
      totalSum: 16000,
      activeCount: 56,
      activeSum: 13200,
    },
    agents: [
      { name: "ניב קובי", count: 44, sum: 10046 },
      { name: "שמש", count: 39, sum: 10115 },
      { name: "אסף בר און", count: 43, sum: 8279 },
      { name: "סימונה", count: 34, sum: 7882 },
      { name: "בן ביטון", count: 26, sum: 6616 },
      { name: "ניב - שמש", count: 23, sum: 6478 },
      { name: "חן בר און", count: 25, sum: 4255 },
      { name: "אוריאל כהן", count: 24, sum: 4241 },
    ],
    monthAgents: [
      { name: "שמש", count: 18, sum: 4200 },
      { name: "ניב קובי", count: 16, sum: 3800 },
      { name: "סימונה", count: 12, sum: 2650 },
      { name: "אסף בר און", count: 11, sum: 2400 },
      { name: "אוריאל כהן", count: 8, sum: 1450 },
      { name: "בן ביטון", count: 7, sum: 1100 },
      { name: "חן בר און", count: 5, sum: 250 },
      { name: "ניב - שמש", count: 4, sum: 150 },
    ],
    companies: [
      { name: "מגדל", count: 140 },
      { name: "הראל", count: 136 },
      { name: "הפניקס", count: 119 },
      { name: "כלל", count: 77 },
      { name: "איילון", count: 22 },
      { name: "מנורה", count: 16 },
      { name: "הכשרה", count: 12 },
    ],
    sources: [
      { name: "לקוחות ליבה", count: 119 },
      { name: "שיחות נכנסות", count: 109 },
      { name: "רועי אזולאי", count: 84 },
      { name: "קפמיין אישי", count: 50 },
      { name: "לידים קרים", count: 27 },
      { name: "קמפיין שמש", count: 17 },
      { name: "אורשן משכנתאות", count: 11 },
    ],
    pendingRows: [
      {
        name: "חיים פאטיטיף",
        agent: "אוריאל כהן",
        product: "אכ\"ע",
        premium: 1450,
        date: "2026-03-12",
      },
      {
        name: "תקווה פרץ",
        agent: "רועי ברודוגו",
        product: "משכנתא",
        premium: 1348,
        date: "2026-03-04",
      },
      {
        name: "מוחמד אבו ראס",
        agent: "ניב קובי",
        product: "תאונות",
        premium: 606,
        date: "2026-03-17",
      },
      {
        name: "ריבה טיטשוולי",
        agent: "ניב קובי",
        product: "משכנתא",
        premium: 580,
        date: "2026-02-17",
      },
      {
        name: "חיכמת עבאס",
        agent: "אוריאל כהן",
        product: "משכנתא",
        premium: 500,
        date: "2026-03-25",
      },
      {
        name: "סימה אהרוני",
        agent: "אוריאל כהן",
        product: "בריאות",
        premium: 500,
        date: "2026-03-29",
      },
      {
        name: "אפרת ג'ובני",
        agent: "שמש",
        product: "בריאות",
        premium: 399,
        date: "2026-03-10",
      },
      {
        name: "סיגלית אלון",
        agent: "שמש",
        product: "בריאות",
        premium: 314,
        date: "2026-03-25",
      },
    ],
    activePolicies: [
      {
        key: "demo|בריאות|ניב קובי|2026-03-01",
        client: "ישראל ישראלי",
        product: "בריאות + מחלות קשות",
        company: "מגדל",
        premium: 1850,
        agent: "ניב קובי",
      },
    ],
    fileName: null,
    syncedAt: new Date().toISOString(),
    source: "demo",
  };
}
